var name = prompt('Give a name: ');
var surName = prompt('Give a Surname: ');
var age = prompt('Age (num): ');
var sms = alert('Ready for the Test !');
var sms1 = alert('3');
var sms2 = alert('2');
var sms3 = alert('1');
var test1 = prompt('15 + 20 = ?');
var test2 = prompt('30 - 15 = ?');
var test3 = prompt('10 * 10 = ?');
var test4 = prompt('9 / 3 = ?');
var test5 = prompt('10 % 3 = ?');
var ednTest = alert('Check your answers on console bar ! (F12)');
console.log('Your name: ' + name);
console.log('Your surname: ' + surName);
console.log('Age: ' + age);
console.log('Answer: ' + (15 + 20) + ' Your answer: ' + test1);
console.log('Answer: ' + (30 - 15) + ' Your answer: ' + test2);
console.log('Answer: ' + (10 * 10) + ' Your answer: ' + test3);
console.log('Answer: ' + (9 / 3) + ' Your answer: ' + test4);
console.log('Answer: ' + (10 % 3 ) + ' Your answer: ' + test5);
35 == test1 ? console.log('1) ' + true) : console.log('1) ' + false); 
15 == test2 ? console.log('2) ' + true) : console.log('2) ' + false); 
100 == test3 ? console.log('3) ' + true) : console.log('3) ' + false); 
3 == test4 ? console.log('4) ' + true) : console.log('4) ' + false); 
1 == test5 ? console.log('5) ' + true) : console.log('5) ' + false);  
console.log('1 correct answer: 1 ball = D mark');
console.log('2 correct answer: 2 ball = D mark');
console.log('3 correct answer: 3 ball = C mark');
console.log('4 correct answer: 4 ball = B mark');
console.log('5 correct answer: 5 ball = A mark');
var result = prompt('How many answers correct: (num) ?');
1 == result ? console.log('D mark - stupid') : false;
2 == result ? console.log('D mark - loser') : false;
3 == result ? console.log('C mark - less loser') : false;
4 == result ? console.log('B mark - not bad') : false;
5 == result ? console.log('A mark - perfect') : false;
console.log(result);
